config/routes.rb
Rails.application.routes.draw do
  namespace :tenant_admin do
    get 'dashboard/index'
  end
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :admin do
    root "dashboard#index"
    get "dashboard", to: "dashboard#tenant_dashboard" 
    resources :users, only: %i[new create index]
    resources :tenants, only: %i[new create show]
    resources :reports, only: %i[index]
  end

  namespace :tenant_admin do
    root "tenants#index"
    resources :tenants, only: %i[new create show]
    get 'dashboard', to: 'dashboard#index'
    get 'users_list', to: 'dashboard#users_list'
    get 'projects_list', to: 'dashboard#projects_list'
    get 'task_list', to: 'dashboard#task_list'
  end

  resources :projects do
    resources :tasks
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        delete 'logout', to: 'sessions#destroy'
        post 'login', to: 'sessions#create'
      end
      # devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :projects, only: %i[index show create update destroy] do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
     end
    end
  end

  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize :dashboard, :index?
  end

  def tenant_dashboard
    # @tenants = Tenant.all
    # authorize @tenants
  end
end

app/controllers/tenant_admin/dashboard_controller.rb
class TenantAdmin::DashboardController < ApplicationController
    before_action :authenticate_user!
    # before_action :authorize_tenant_admin
    before_action :set_tenant
    before_action :switch_tenant

    def index
      @tenants = Tenant.all
      authorize @tenants
    end

    def users_list
      @users = @tenant.users
    end

    def projects_list
      @projects = Project.where(user_id: @tenant&.users)
    end

    def task_list
      @tasks = Task.where(assigned_to_id: @tenant&.users)
    end

  private

    def authorize_tenant_admin
      redirect_to root_path, alert: 'Access Denied' unless current_user.tenant_admin?
    end

    def set_tenant
      @tenant = Tenant.find(params[:id])
      authorize @tenant
    end

    def switch_tenant
      Apartment::Tenant.switch!(@tenant.name) if @tenant
    end
end

app/controllers/tenant_admin/tenants_controller.rb
class TenantAdmin::TenantsController < ApplicationController

  def index
    @tenants = Tenant.all
  end

  # GET /tenant/:id
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new()
    authorize @tenant
  end

  # POST /tenants
  def create
    @tenant = Tenant.create!(tenant_params)
    authorize @tenant
    if @tenant
      redirect_to tenant_admin_tenants_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  private

    def tenant_params
      params.require(:tenant).permit(:name)
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/tenant_admin/dashboard_helper.rb
module TenantAdmin::DashboardHelper
end

app/helpers/tenant_admin/tenants_helper.rb
module TenantAdmin::TenantsHelper
end

app/views/tenant_admin/dashboard/projects_list.html.erb
<h2>Projects</h2>
<%= link_to "New project", new_project_path, class: "nav-link" %>
<table>
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td>
        <td><%#= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_project_path(project, tenant_id: @tenant) %></td>
        <td><%#= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tenant_admin/dashboard/task_list.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Story Point</th>
      <th>Assigned To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.story_point %></td>
        <td><%= task.assigned_to.email if task.assigned_to %></td>
        <td><%#= link_to 'Show', task %></td>
        <td><%#= link_to 'Edit', task %></td>
        <td><%#= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tenant_admin/dashboard/users_list.html.erb
<h1>Tenant Admin Dashboard</h1>
<h1>Users</h1>
<p><%= link_to "New User", new_admin_user_path, class: "nav-link" %></p>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Tenant DB</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user&.first_name %></td>
        <td><%= user&.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_role %></td>
        <td><%= user&.tenant&.name%></td>
        <td><%#= link_to 'Show', [@project, task] %></td>
        <td><%#= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%#= link_to 'Destroy', [@project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>