config/routes.rb
Rails.application.routes.draw do
  namespace :tenant_admin do
    get 'dashboard/index'
  end
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :admin do
    root "dashboard#index"
    get "dashboard", to: "dashboard#tenant_dashboard" 
    resources :users, only: %i[new create index]
    resources :tenants, only: %i[new create show]
    resources :reports, only: %i[index]
  end

  namespace :tenant_admin do
    root "tenants#index"
    resources :tenants, only: %i[new create show]
    get 'dashboard', to: 'dashboard#index'
    get 'users_list', to: 'dashboard#users_list'
    get 'projects_list', to: 'dashboard#projects_list'
    get 'task_list', to: 'dashboard#task_list'
  end

  resources :projects do
    resources :tasks
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        delete 'logout', to: 'sessions#destroy'
        post 'login', to: 'sessions#create'
      end
      # devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :projects, only: %i[index show create update destroy] do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
     end
    end
  end

  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true

  has_many :tasks, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  scope :completed, -> { where(status: 'completed') }
  scope :inprogress, -> { where(status: 'inprogress') }

  def average_task_completion_time
    # self.tasks.completed.average('end_date - start_date')
    tasks = Task.where(project_id: self.id)
    tasks.completed.average('end_date - start_date')
  end

  def total_story_points
    # self.tasks.sum(:story_point)
    tasks = Task.where(project_id: self.id)
    tasks.sum(:story_point)
  end

  # enum status: { new: "new", inprogress: "inprogress", complete: "complete" }, _prefix: :status
  
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
	before_action :set_project
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authorize_project, only: %i[show edit update destroy]

  # GET/projects.json
  def index
    @projects = policy_scope(Project)
    render json: @projects
  end

  # GET /p@projects = policy_scope(Project)rojects/1.json
  def show
  end

  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    authorize @project

    if @project.save
    	render json: @project, status: :created
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1.json
  def update
  	if @project.update(project_params)
      render json: @project
    else
    	render json: @project.errors, status: '401'
    end
  end

  # DELETE /projects/1.json
  def destroy
    authorize @project 
    if @project.destroy!
      render json: { message: 'Project was successfully deleted.' }, status: "200"
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :status, :start_date, :end_date, :user_id)
    end

    def authorize_project
      authorize @project
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /p@projects = policy_scope(Project)rojects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    Rails.logger.info "Current schema after switch:====================== #{ActiveRecord::Base.connection.current_schema}"
    Rails.logger.info "User.connection.schema_search_path:====================== #{User.connection.schema_search_path}"

    @user =  project_params[:user_id] ? User.find( project_params[:user_id]) : current_user

    @project = @user.projects.new(project_params)
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :start_date, :end_date, :user_id, :status)
    end

    def authorize_project
      authorize @project
    end
end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Example Form</h5>
          <%= form_with model: project, class: 'needs-validation' do |form| %>
            <% if project.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
                <ul>
                  <% project.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="mb-3">
              <%= form.label :title, class: 'form-label' %>
              <%= form.text_field :title, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a project title.
              </div>
            </div>
            <div class="mb-3">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a description.
              </div>
            </div>
            <div class="mb-3">
              <%= form.label :start_date, class: 'form-label' %>
              <%= form.date_field :end_date, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a project start date.
              </div>
            </div>
            <div class="mb-3">
              <%= form.label :end_date, class: 'form-label' %>
              <%= form.date_field :end_date, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a project end date.
              </div>
            </div>

            <div class="mb-3">
              <%= form.label :user_id %>
              <%= form.collection_select :user_id, UserRole.is_admin&.users, :id, :email, {include_blank: true, class: 'form-control'} %>
            </div>

            <div class="mb-3">
              <%= form.label :status, class: 'form-label' %>
              <%= form.select(:status, ["new", "inprogress", "complete"], include_blank: false, class: 'form-control') %>
            </div>
            <%= form.submit 'Submit', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict'
    var forms = document.querySelectorAll('.needs-validation')
    Array.prototype.slice.call(forms).forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }
        form.classList.add('was-validated')
      }, false)
    })
  })()
</script>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.title %>

    <strong>Description:</strong>
    <%= project.description %>

  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Projects</h5>
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Description</th>
                  <th scope="col">Status</th>
                  <th scope="col">Start Date</th>
                  <th scope="col">End Date</th>
                  <th colspan="3">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @projects.each do |project| %>
                  <tr>
                    <td><%= project.title %></td>
                    <td><%= project.description %></td>
                    <td><%= project.status %></td>
                    <td><%= project.start_date %></td>
                    <td><%= project.end_date %></td>
                    <td><%= link_to 'Show', project_path(project) %></td>
                    <td><%= link_to 'Edit', edit_project_path(project) %></td>
                    <td><%= link_to 'Destroy', project_path(project), method: :delete, data: { turbo_method: :delete }%></td>
                  </tr>
                <% end %>
                <!-- Add more rows as needed -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project), class: "link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %> |
  <%= link_to "Back to projects", projects_path, class: "link-offset-2 link-underline link-underline-opacity-0" %> | 
  <%= link_to "task", project_tasks_path(@project), class: "link-offset-2 link-underline link-underline-opacity-1" %> |
  <%= link_to "Destroy this project", @project, method: :delete, class: "link-offset-2 link-underline link-underline-opacity-0nav-link" %>
</div>