config/routes.rb
Rails.application.routes.draw do
  namespace :tenant_admin do
    get 'dashboard/index'
  end
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations'}
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :admin do
    root "dashboard#index"
    get "dashboard", to: "dashboard#tenant_dashboard" 
    resources :users, only: %i[new create index]
    resources :tenants, only: %i[new create show]
    resources :reports, only: %i[index]
  end

  namespace :tenant_admin do
    root "tenants#index"
    resources :tenants, only: %i[new create show]
    get 'dashboard', to: 'dashboard#index'
    get 'users_list', to: 'dashboard#users_list'
    get 'projects_list', to: 'dashboard#projects_list'
    get 'task_list', to: 'dashboard#task_list'
  end

  resources :projects do
    resources :tasks
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        delete 'logout', to: 'sessions#destroy'
        post 'login', to: 'sessions#create'
      end
      # devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :projects, only: %i[index show create update destroy] do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
     end
    end
  end

  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_subnavbar.html.erb
<!-- Sub-Navbar -->
<% if user_signed_in? && current_user.has_role?('admin')%>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="subNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "New User", new_admin_user_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "New project", new_project_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", admin_users_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

<!-- Sub-Navbar -->
<% if user_signed_in? && current_user.has_role?('tenant_admin') && @tenant.present? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="subNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'User List', tenant_admin_users_list_path(id: @tenant), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Project List', tenant_admin_projects_list_path(id: @tenant), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Task List', tenant_admin_task_list_path(id: @tenant), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

<% if user_signed_in? && ( current_user.has_role?('team_member') || current_user.has_role?('project_manager'))%>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="subNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Promanage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"> &nbsp; <%= current_user&.tenant_id ? Apartment::Tenant.current : 'public' %> &nbsp; &nbsp; &nbsp; <%= current_user&.email%></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mainNavbar">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= button_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo: :false }%>
            </li>&nbsp; &nbsp; &nbsp;
            <li class="nav-item">
              <%= link_to "Reports", admin_reports_path, class: "link-info" %>
            </li>
          <% end %>
          
          <%- unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

   <%= render 'layouts/subnavbar' %>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>